// GENERATED by `keel eslint-config` from keel.config `limits`. Do not edit by
// hand — change keel.config and regenerate. Severity is "warn" by design: keel's
// lint ratchet blocks these on changed lines and grandfathers legacy.
// Spread this into your root ESLint flat config:
//   import keel from "./eslint.config.keel.mjs";
//   export default [ ...keel, /* your rules */ ];

// cognitive-complexity (limits.cognitive=15) via eslint-plugin-sonarjs when
// present; keel provisions it on adopt. The guarded dynamic import keeps the
// lint run alive if the plugin is ever absent (it just no-ops).
const cognitive = await (async () => {
  try {
    const mod = await import("eslint-plugin-sonarjs");
    const sonarjs = mod.default || mod;
    if (sonarjs && typeof sonarjs === "object" && sonarjs.rules?.["cognitive-complexity"]) {
      return [{ files: ["**/*.{ts,tsx,js,jsx,mjs,cjs}"], plugins: { sonarjs }, rules: { "sonarjs/cognitive-complexity": ["warn", 15] } }];
    }
    return [];
  } catch {
    return [];
  }
})();

export default [
  {
    files: ["**/*.{ts,tsx,js,jsx,mjs,cjs}"],
    rules: {
      "max-lines-per-function": ["warn", { max: 100, skipBlankLines: true, skipComments: true }],
      "complexity": ["warn", 8],
      "max-depth": ["warn", 4],
      "max-params": ["warn", 4],
    },
  },
  ...cognitive,
];
